<a href="https://colab.research.google.com/github/CaMunozS/deep_learning/blob/main/12_Aplicaciones_de_transformers_con_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aplicaciones de transformers con `pipeline`

## Sesión 6: Transformers / LLMs

En este notebook usaremos modelos preentrenados basados en transformers mediante una interfaz de alto nivel.

La idea es centrarnos en el **uso práctico** de modelos modernos para tareas de lenguaje, sin implementar la arquitectura desde cero.

Este notebook conecta con dos sesiones previas del curso:

- en la **sesión 4**, trabajamos secuencias con RNN, LSTM y GRU,
- en la **sesión 5**, trabajamos con modelos preentrenados en visión.

Ahora veremos una versión moderna de esa misma idea en NLP.

## Objetivo pedagógico

Al finalizar este notebook deberíamos ser capaces de:

- usar un modelo transformer preentrenado con una interfaz simple,
- aplicar ese modelo a tareas de NLP de uso común,
- interpretar salidas básicas del modelo,
- reconocer que hoy muchas aplicaciones modernas se apoyan en modelos ya entrenados.

No haremos fine-tuning en este notebook.
La meta es tener una primera experiencia robusta y clara con herramientas modernas.

In [1]:
!pip -q install transformers pillow

## Importamos librerías

Usaremos [`pipeline()`](https://huggingface.co/docs/transformers/en/pipeline_tutorial) de Hugging Face.

`pipeline()` es una interfaz de alto nivel que agrupa:

- el modelo preentrenado,
- el tokenizer o preprocesamiento,
- y el postprocesamiento de la salida.

In [2]:
from transformers import pipeline
import pandas as pd

## Primera tarea: análisis de sentimiento

Una de las tareas más clásicas en NLP es clasificar el sentimiento de un texto.

En Hugging Face, esta tarea está disponible directamente como:

- `sentiment-analysis`

In [3]:
sentiment_classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

## ¿Qué significa el mensaje que apareció?

Cuando ejecutamos:

```python
sentiment_classifier = pipeline("sentiment-analysis")

Hugging Face nos informa que, como no especificamos manualmente un modelo, eligió uno por defecto para esta tarea.
En este caso, el pipeline indica algo como:
`No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english ...`
Eso significa que el sistema seleccionó automáticamente un modelo ya entrenado para análisis de sentimiento.

## ¿Qué es BERT?

**BERT** es una arquitectura de transformers muy influyente en procesamiento de lenguaje natural.

Fue diseñada principalmente para aprender representaciones de texto y luego adaptarse a tareas como:

- clasificación,
- pregunta-respuesta,
- análisis de sentimiento,
- entre otras.

En términos simples, BERT es uno de los modelos que ayudó a consolidar el uso masivo de transformers en NLP.

## ¿Qué es DistilBERT?

**DistilBERT** es una versión más pequeña y más rápida de BERT.

La idea es conservar gran parte del desempeño de BERT, pero usando menos parámetros y menos costo computacional.

Esto se logra mediante un proceso llamado **knowledge distillation** o destilación de conocimiento.

En términos prácticos:

- BERT suele ser más grande,
- DistilBERT suele ser más liviano y más rápido,
- por eso DistilBERT es una opción muy conveniente para demos, notebooks y aplicaciones ligeras.

## Descomponiendo el nombre del modelo

El nombre completo es:

`distilbert-base-uncased-finetuned-sst-2-english`

Podemos leerlo por partes:

- **distilbert**: pertenece a la familia DistilBERT.
- **base**: indica una versión base del modelo, no una versión gigante.
- **uncased**: el modelo no distingue entre mayúsculas y minúsculas.
- **finetuned**: ya fue ajustado para una tarea específica.
- **sst-2**: fue ajustado usando el dataset Stanford Sentiment Treebank 2.
- **english**: está pensado para texto en inglés.

## ¿Qué significa “fine-tuned on SST-2”?

Primero, el modelo fue **preentrenado** de manera general sobre grandes cantidades de texto.

Después, fue **fine-tuned** o ajustado finamente en una tarea concreta:
clasificación de sentimiento.

Para eso se usó **SST-2**, un dataset clásico de análisis de sentimiento en inglés.

Por eso este modelo ya viene especialmente preparado para distinguir entre textos positivos y negativos.

## ¿Qué significa `revision 714eb0f`?

La palabra **revision** se refiere a una versión concreta del repositorio del modelo en Hugging Face.

Esa cadena corta (`714eb0f`) funciona como un identificador de revisión o commit.

La idea es simple:

- el nombre del modelo dice **qué modelo** estamos usando,
- la revisión indica **qué versión exacta** de ese modelo o repositorio quedó seleccionada.

Esto ayuda a la reproducibilidad, porque dos personas pueden cargar exactamente la misma versión del modelo.

## Idea importante para quedarse

Cuando usamos:

```python
pipeline("sentiment-analysis")

no estamos creando un modelo desde cero.
Estamos usando un sistema que automáticamente selecciona:


*   un modelo preentrenado,
*   su tokenizer correspondiente,
*   y una configuración lista para inferencia.

Eso es justamente parte de la potencia del ecosistema moderno:
podemos aplicar modelos avanzados con muy poco código.

In [4]:
texts = [
    "I loved this movie. The acting was excellent.",
    "This film was boring and disappointing.",
    "The notebook was clear and useful."
]

results = sentiment_classifier(texts)
results

[{'label': 'POSITIVE', 'score': 0.9998757839202881},
 {'label': 'NEGATIVE', 'score': 0.9997678399085999},
 {'label': 'POSITIVE', 'score': 0.9997556805610657}]

## ¿Qué observamos?

El pipeline devuelve, para cada texto:

- una etiqueta predicha,
- un score de confianza.

Esto nos permite usar un modelo moderno sin tener que tokenizar manualmente ni definir la arquitectura capa por capa.

In [5]:
df_results = pd.DataFrame({
    "text": texts,
    "prediction": [r["label"] for r in results],
    "score": [r["score"] for r in results]
})

df_results

                                            text prediction     score
0  I loved this movie. The acting was excellent.   POSITIVE  0.999876
1        This film was boring and disappointing.   NEGATIVE  0.999768
2             The notebook was clear and useful.   POSITIVE  0.999756

## Probemos con ejemplos nuevos

Ahora podemos evaluar textos creados por nosotros.

In [6]:
new_texts = [
    "I really enjoyed the class and learned a lot.",
    "The explanation was confusing and too rushed.",
    "The movie had good visuals, but the story was weak."
]

new_results = sentiment_classifier(new_texts)

pd.DataFrame({
    "text": new_texts,
    "prediction": [r["label"] for r in new_results],
    "score": [r["score"] for r in new_results]
})

                                                text prediction     score
0      I really enjoyed the class and learned a lot.   POSITIVE  0.999808
1      The explanation was confusing and too rushed.   NEGATIVE  0.999774
2  The movie had good visuals, but the story was ...   NEGATIVE  0.997508

## Segunda tarea: zero-shot classification

Otra tarea interesante es la **zero-shot classification**.

Aquí el modelo intenta clasificar un texto usando etiquetas que nosotros proponemos, incluso si no entrenamos el modelo específicamente para ese conjunto de clases.

In [7]:
zero_shot_classifier = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli and revision d7645e1.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

## ¿Qué es `facebook/bart-large-mnli`?

En este caso, Hugging Face seleccionó por defecto el modelo:

`facebook/bart-large-mnli`

Podemos leerlo por partes:

- **facebook**: indica la organización o autor que publicó originalmente el modelo en Hugging Face.
- **bart**: corresponde a la familia **BART**, un modelo transformer de tipo encoder-decoder.
- **large**: indica una versión grande del modelo.
- **mnli**: significa que fue ajustado usando el dataset **Multi-Genre Natural Language Inference (MNLI)**.

La idea importante es esta:

este modelo no fue entrenado directamente como un clasificador tradicional de temas o categorías, sino como un modelo de **inferencia en lenguaje natural**.

Eso permite reutilizarlo para **zero-shot classification**.

En términos simples, el modelo evalúa si un texto es compatible con una etiqueta candidata formulada como una hipótesis, por ejemplo:

- texto: `"This course session introduces transformers and language models."`
- hipótesis: `"This text is about education."`

Luego estima qué tan bien esa hipótesis está apoyada por el texto.

Por eso `facebook/bart-large-mnli` funciona tan bien como modelo base para clasificación zero-shot.

In [8]:
candidate_labels = ["education", "entertainment", "sports", "technology"]

text = "This course session introduces transformers, attention, and language models."

zero_shot_result = zero_shot_classifier(text, candidate_labels)
zero_shot_result

{'sequence': 'This course session introduces transformers, attention, and language models.',
 'labels': ['education', 'technology', 'entertainment', 'sports'],
 'scores': [0.8404918313026428,
  0.10409558564424515,
  0.044874679297208786,
  0.010537863709032536]}

## Interpretación

El modelo compara el texto con las etiquetas candidatas y estima cuál parece más adecuada.

Esto muestra una capacidad moderna muy distinta a los clasificadores tradicionales entrenados desde cero sobre un conjunto fijo de clases.

## Y en español?

In [9]:
from transformers import pipeline

zero_shot_classifier = pipeline(
    "zero-shot-classification",
    model="Recognai/bert-base-spanish-wwm-cased-xnli"
)

texto = "Esta sesión introduce transformers, atención y modelos de lenguaje."
labels = ["educación", "deporte", "tecnología", "entretenimiento"]

zero_shot_classifier(texto, labels)

config.json:   0%|          | 0.00/834 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/439M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: Recognai/bert-base-spanish-wwm-cased-xnli
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/528 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

{'sequence': 'Esta sesión introduce transformers, atención y modelos de lenguaje.',
 'labels': ['entretenimiento', 'tecnología', 'educación', 'deporte'],
 'scores': [0.4097205698490143,
  0.3809944689273834,
  0.12171562016010284,
  0.08756941556930542]}

## Tercera tarea: question answering

También podemos usar transformers preentrenados para responder preguntas a partir de un contexto dado.

In [10]:
qa_pipeline = pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

## ¿Qué es `distilbert/distilbert-base-cased-distilled-squad`?

Para la tarea de **question answering**, Hugging Face seleccionó por defecto el modelo:

`distilbert/distilbert-base-cased-distilled-squad`

Podemos leerlo por partes:

- **distilbert**: pertenece a la familia **DistilBERT**, una versión más liviana y rápida de BERT.
- **distilbert-base**: corresponde a una versión base del modelo.
- **cased**: el modelo **sí distingue mayúsculas y minúsculas**.
- **distilled**: fue obtenido mediante **knowledge distillation**, es decir, conservando gran parte del conocimiento de un modelo mayor en una versión más compacta.
- **squad**: fue ajustado para la tarea de pregunta-respuesta usando el dataset **SQuAD**.

La idea importante es esta:

este modelo ya fue preparado para responder preguntas a partir de un **contexto dado**.

Por eso, cuando usamos el pipeline de `question-answering`, el modelo intenta encontrar dentro del texto el fragmento que mejor responde la pregunta.

In [11]:
context = """
Transformers are deep learning architectures based on attention mechanisms.
They became highly influential in natural language processing and later extended to vision, audio, and multimodal tasks.
"""

question = "What is the main mechanism behind transformers?"

qa_result = qa_pipeline(question=question, context=context)
qa_result

{'score': 0.6876665949821472,
 'start': 55,
 'end': 75,
 'answer': 'attention mechanisms'}

## Comentario importante

En este caso, el modelo no está “inventando” libremente una respuesta:
está intentando encontrar una respuesta dentro del contexto entregado.

Esto es distinto de la generación abierta de texto.

## Y en español?

In [12]:
from transformers import pipeline

qa_pipeline = pipeline(
    "question-answering",
    model="mrm8488/bert-multi-cased-finetuned-xquadv1",
    tokenizer="mrm8488/bert-multi-cased-finetuned-xquadv1"
)

contexto = """
Los transformers son arquitecturas de deep learning basadas en mecanismos de atención.
Primero fueron muy influyentes en procesamiento de lenguaje natural y luego también se extendieron a visión.
"""

pregunta = "¿En qué mecanismo se basan los transformers?"

qa_pipeline(question=pregunta, context=contexto)

config.json:   0%|          | 0.00/657 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/711M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForQuestionAnswering LOAD REPORT from: mrm8488/bert-multi-cased-finetuned-xquadv1
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/40.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

{'score': 0.9580803513526917,
 'start': 64,
 'end': 86,
 'answer': 'mecanismos de atención'}

## Cuarta tarea: generación de texto

Muchos modelos modernos de lenguaje también se usan para continuar o generar texto.

In [13]:
text_generator = pipeline("text-generation", model="distilgpt2")

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: distilgpt2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
transformer.h.{0, 1, 2, 3, 4, 5}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

## ¿Qué es `distilbert/distilgpt2`?

Para la tarea de **generación de texto**, en este ejemplo usamos el modelo:

`distilbert/distilgpt2`

Podemos leerlo por partes:

- **distilbert**: indica la organización o comunidad que publica este modelo en Hugging Face.
- **distilgpt2**: corresponde a **DistilGPT2**, una versión más liviana de GPT-2.

La idea importante es esta:

- **GPT-2** es un modelo transformer orientado a **generación de texto**.
- **DistilGPT2** es una versión más pequeña y más rápida, obtenida mediante **knowledge distillation**.
- Por eso resulta útil para demos y notebooks donde queremos generar texto sin usar un modelo demasiado pesado.

A diferencia de los modelos usados antes para clasificación o pregunta-respuesta, aquí el objetivo no es asignar una etiqueta ni buscar una respuesta en un contexto, sino **continuar texto** generando nuevos tokens.

En otras palabras, este modelo toma un texto inicial y predice cómo podría seguir.

In [14]:
generated = text_generator(
    "Deep learning models based on attention are useful because",
    max_new_tokens=40,
    num_return_sequences=1
)

generated

Passing `generation_config` together with generation-related arguments=({'num_return_sequences', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=40) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': 'Deep learning models based on attention are useful because they help to provide better performance for the learner by making them easier to learn.\n\n\nThe learning model is based on the fact that the learner is learning from the knowledge of a particular'}]

## Y en español?

In [15]:
generator = pipeline(
    "text-generation",
    model="DeepESP/gpt2-spanish"
)

generator("Los transformers son importantes porque", max_new_tokens=40)

config.json:   0%|          | 0.00/914 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/261M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: DeepESP/gpt2-spanish
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |
transformer.h.{0...11}.attn.bias        | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/115 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/262 [00:00<?, ?B/s]

Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=40) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': 'Los transformers son importantes porque están en el tercer escalón; las mejores son las mejores porque son las mejores porque son las mejores porque son las mejores porque son las mejores porque son más que las mejores porque son las mejores porque son las'}]

## ¿Qué aprendimos hasta aquí?

Con la misma idea general de transformer preentrenado podemos abordar tareas muy distintas:

- análisis de sentimiento,
- clasificación flexible,
- pregunta-respuesta,
- generación de texto.

Eso ayuda a entender por qué los transformers pasaron a ser tan influyentes en NLP.

## Comparación conceptual con la sesión 4

En la sesión 4 usamos un enfoque más clásico para texto:

- tokenización simple,
- embedding,
- LSTM,
- capa densa final.

Aquí, en cambio:

- usamos modelos ya preentrenados,
- con tokenizadores propios,
- y con capacidades más amplias.

El punto de partida es mucho más fuerte.

## Puente con la sesión 5

En la sesión 5 reutilizamos modelos preentrenados para imágenes.

Aquí estamos haciendo algo conceptualmente muy parecido, pero en lenguaje:

- partimos desde un modelo ya entrenado,
- no desde pesos aleatorios,
- y lo usamos en tareas concretas.

## Cierre

En este notebook vimos cómo usar modelos transformer preentrenados mediante `pipeline()`.

La idea central fue:

- no entrenar desde cero,
- usar herramientas de alto nivel,
- explorar tareas modernas de NLP de forma accesible.

Este es un patrón muy representativo del ecosistema actual de modelos de lenguaje.

## Bonus: una mirada a visión con transformers

Los transformers no se quedaron solo en NLP.

También existen modelos para visión, por ejemplo para clasificación de imágenes.

In [16]:
image_classifier = pipeline("image-classification")

No model was supplied, defaulted to google/vit-base-patch16-224 and revision 3f49326.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

In [17]:
image_classifier("https://huggingface.co/datasets/Narsil/image_dummy/raw/main/parrots.png")

[{'label': 'macaw', 'score': 0.9905233979225159},
 {'label': 'African grey, African gray, Psittacus erithacus',
  'score': 0.00560346944257617},
 {'label': 'toucan', 'score': 0.001056905835866928},
 {'label': 'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita',
  'score': 0.0006811478524468839},
 {'label': 'lorikeet', 'score': 0.0006714339251630008}]